version: '3.9'

services:
  postgres:
    image: postgres:13.4-alpine
    restart: unless-stopped
    env_file: ./.env
    networks:
      - cart
    volumes:
      - ./docker/volumes/pgdata/dataregion:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - 5432:5432

  api:
    depends_on:
      - postgres
    deploy:
      restart_policy:
        condition: on-failure
        delay: 2s
        max_attempts: 5
        window: 60s
    build:
      context: .
      dockerfile: apps/api/Dockerfile
    volumes:
      - .:/app
      - exclude:/app/node_modules
    networks:
      - cart
    ports:
      - 3333:3333
    env_file: ./.env

volumes:
  exclude:
networks:
  cart:
    driver: bridge
